spring:
  datasource:
    url: jdbc:h2:mem:customer
    username: user
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

